import React, { useState, useEffect} from 'react'
import {useNavigate} from 'react-router-dom'

import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';
import { PostForm } from "../constants/interfaces";

const CreatePost = () => {
    const navigate = useNavigate();

    const [form, setForm] = useState<PostForm>({
        name: '',
        prompt: '',
        photo: ''
    });

    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleSubmit = () => {

    }

    const handleChange = (e) => {

    }

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-darkgrey text-[32px]">Create</h1>
                <p className="mt-2 text-grey text-[16px] max-w-[500px]">Create imaginative and visually stunning images generated by DALL-E AI and share them with the community.</p>
            </div>
            <form onSubmit={handleSubmit} className="my-16 max-w-3xl">
                <div className="flex flex-col gap-5">
                    <FormField labelName="Your name" type="text" name="name" placeholder="John Doe" value={form.name} handleChange={handleChange}/>
                    <FormField labelName="Prompt" type="text" name="prompt" placeholder={getRandomPrompt()} value={form.prompt} handleChange={handleChange} isSupriseMe/>
                </div>
            </form>
        </section>
    )
}
export default CreatePost
