import React, { useState, useEffect} from 'react'
import {useNavigate} from 'react-router-dom'

import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';
import { PostForm } from "../constants/interfaces";

const randomPrompt = getRandomPrompt("");

const CreatePost = () => {
    const navigate = useNavigate();

    const [form, setForm] = useState<PostForm>({
        name: '',
        prompt: '',
        photo: ''
    });

    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleSubmit = () => {

    }

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setForm({...form, [e.target.name]: e.target.value});
    }

    const handleSurpriseMe = () => {
        const prompt = getRandomPrompt(form.prompt);
        setForm({...form, prompt : prompt});
    }

    const generateImg = () => {

    }

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-darkgrey text-[32px]">Create</h1>
                <p className="mt-2 text-grey text-[16px] max-w-[500px]">Create imaginative and visually stunning images generated by DALL-E AI and share them with the community.</p>
            </div>
            <form onSubmit={handleSubmit} className="my-16 max-w-3xl">
                <div className="flex flex-col gap-5">
                    <FormField labelName="Your name" type="text" name="name" placeholder="John Doe" value={form.name} handleChange={handleChange}/>
                    <FormField labelName="Prompt" type="text" name="prompt" placeholder={randomPrompt} value={form.prompt} handleChange={handleChange} isSurpriseMe handleSurpriseMe={handleSurpriseMe}/>
                    <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 w-64 p-3 h-64 flex justify-center items-center">
                        {form.photo ? (<img src={form.photo} alt={form.prompt} className="w-full h-full object-contain"/>)
                            : (<img
                            src={preview} alt="preview" className="w-9/12 h-9/12 object-contain opacity-40"/>)}
                        {generatingImg && <div className="absolute inset-0 z-9 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                            <Loader/>
                        </div>}
                    </div>
                </div>
                <div className="mt-5 flex gap-5">
                    <button type="button" onClick={generateImg} className="text-white bg-green-600 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center">
                        {generatingImg ? 'Generating...' : 'Generate Image'}
                    </button>
                </div>
                <div className="mt-10">
                    <p className="mt-2 text-grey text-[14px]">Once you have create the image you want, you can share it with others in the community</p>
                    <button type="submit" className="mt-4 text-white bg-accent font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center">{loading? 'Sharing...' : 'Share with the community'}</button>
                </div>
            </form>
        </section>
    )
}
export default CreatePost
